---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
    - hostname: name=ubuntu

    - lineinfile: dest=/etc/apt/sources.list.d/docker.list create=yes line="deb https://get.docker.io/ubuntu docker main"
    - apt_key: keyserver=keyserver.ubuntu.com id=0xD8576A8BA88D21E9
    - apt: pkg={{item}} update_cache=yes
      with_items:
        - apache2
        - php5
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-json
        - php5-mcrypt
        - php5-mongo
        - php5-mysql
        - php5-xdebug
        - php-pear
        - byobu
        - vim
        - mysql-server
        - lxc-docker

    - lineinfile: dest=/etc/apache2/envvars regexp="^export APACHE_RUN_USER" line="export APACHE_RUN_USER=vagrant"
    - lineinfile: dest=/etc/apache2/envvars regexp="^export APACHE_RUN_GROUP" line="export APACHE_RUN_GROUP=vagrant"

    - lineinfile : dest=/etc/apache2/sites-available/000-default.conf regexp="DocumentRoot" line="DocumentRoot /vagrant/www"
    - lineinfile : dest=/etc/apache2/sites-available/000-default.conf line={{item}} insertafter=EOF
      with_items:
        - "'<Directory /vagrant/www>'"
        - "'AllowOverride All'"
        - "'Require all granted'"
        - "'</Directory>'"

    - command: /usr/sbin/a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load
    - command: /usr/sbin/a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
    - command: /usr/sbin/a2ensite default-ssl creates=/etc/apache2/sites-enabled/default-ssl.conf

    - lineinfile : dest=/etc/apache2/sites-available/default-ssl.conf regexp="DocumentRoot" line="DocumentRoot /vagrant/www"

    - lineinfile : dest=/etc/php5/apache2/php.ini regexp=";?date\.timezone.*" line="date.timezone = Asia/Tokyo"

    - service: name=apache2 state=restarted
    - service: name=mysql state=restarted
